# This rule is not used by the project lbconfig-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over lb.lbconfig.carlosedp.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lbconfig-operator
    app.kubernetes.io/managed-by: kustomize
  name: externalloadbalancer-admin-role
rules:
  - apiGroups:
      - lb.lbconfig.carlosedp.com
    resources:
      - externalloadbalancers
    verbs:
      - "*"
  - apiGroups:
      - lb.lbconfig.carlosedp.com
    resources:
      - externalloadbalancers/status
    verbs:
      - get
